### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nabulator** [finalarcadia/openpad#6]
Any type of license that comes with the project? 
I know the project name contains "open" but no open license could mean no open development. Technically, if you don't have a license, code/text is still copyrighted and not truly open-source.  

Just asking to be safe. 
Here is a convenient [list](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) of open licenses to choose from if you so are so inclined.

**Comment by gabe-fz** [comment]
MIT license added.
